### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by FelipeFMA** [lrabe/bd-prochot#1]
I'd like to know what I need to do in order to use it

**Comment by lrabe** [comment]
Hi Felipe! 
Compile the program using Visual Studio. Run with "enable" or "disable" parameters from the Windows command line (see https://github.com/lrabe/bd-prochot/blob/c220939ec7f1aa044982af0721277903d4618457/bd-prochot/bd-prochot.cpp#L98 ) 
You need to obtain the WinRing0x64.dll / WinRing0.dll and place it next to the compiled binary. I can't provide the .dll file due to copyright.

**Comment by FelipeFMA** [comment]
Ouch, I feel so dumb, lol. My idea was to make a script that runs your program every 5 seconds because my Dell laptop somehow manages to turn BDPROCHOT on by itself from time to time. I did a similar workaround on Linux, and it worked fine, but now I talked with the creator of ThrottleStop, and he made a beta version that manages to lock it off. Thank you anyways!
